[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Minimal bytecode profile for HyperEVM (3M block gas limit)
[profile.small]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 1
via_ir = false

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
hyper_mainnet = "${RPC_URL_HYPER_MAINNET}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 1, url = "https://api.etherscan.io/api" }
hyperevm_mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 999, url = "https://api.etherscan.io/v2/api?chainid=999" }
